### User sign up end point
POST http://127.0.0.1/v1/user 
Content-Type: application/json


{
    "name": "Duc Huy",
    "company": "Hoa Sen",
    "address" : "quang trung",
    "phone" : "111222333",
    "email" : "user3@gmail.com",
    "password" : "hsu123456"
}


### User sign in end point
POST http://127.0.0.1/v1/user/login
Content-Type: application/json


{
    "email" : "user3@gmail.com",
    "password" : "hsu01123"
}
### User user profile endpoint
GET http://127.0.0.1/v1/user/login
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIzQGdtYWlsLmNvbSIsImlhdCI6MTYxNzk3ODIzMywiZXhwIjoxNjE3OTc5MTMzfQ.S0HXReCcFsDf5en-Q1BN-M2KfsE4AqTifvNgFvdacC8

{
    "email" : "user3@gmail.com",
    "password" : "hsu123456"
}

### GET refresh tokens
GET http://127.0.0.1/v1/user/login
Authorization: : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXI0QGdtYWlsLmNvbSIsImlhdCI6MTYxODIzNzQ0MCwiZXhwIjoxNjE4MjM4MzQwfQ.pKzgHDhLUyRyRmp1HOwPN7TTPhW4c7JYWzpjrLJjCRY


### User RESET PASSWORD
POST http://127.0.0.1/v1/user/reset-password
Content-Type: application/json

{
    "email" : "user3@gmail.com",
}

### UPDATE NEW PASSWORD by using pin 
PATCH  http://127.0.0.1/v1/user/reset-password
Content-Type: application/json

{
    "email" : "user3@gmail.com",
    "pin" : 684613   ,
    "newPassword" : "hsu01123"
}



### LOG OUT endpoints
DELETE   http://127.0.0.1/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIzQGdtYWlsLmNvbSIsImlhdCI6MTYxODU5MjAxMiwiZXhwIjoxNjE4NTkzODEyfQ.yqYLDB-1CbumaQr2ojt1O81QqdPs7KOMjF-R8xlPjWc

################# ticket ######

### CREATE new ticket endpoints
POST    http://127.0.0.1/v1/ticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIzQGdtYWlsLmNvbSIsImlhdCI6MTYxODU5MjAxMiwiZXhwIjoxNjE4NTkzODEyfQ.yqYLDB-1CbumaQr2ojt1O81QqdPs7KOMjF-R8xlPjWc


{
    "subject" : "user3@gmail.com",
    "sender" : "duc huy",
    "message" : "this is test message22 from minh doan user" 
}

### GET ALL TICKET INFORMATION
GET    http://127.0.0.1/v1/ticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIzQGdtYWlsLmNvbSIsImlhdCI6MTYxODU5MjAxMiwiZXhwIjoxNjE4NTkzODEyfQ.yqYLDB-1CbumaQr2ojt1O81QqdPs7KOMjF-R8xlPjWc


#### GET TICKET BY SPECIFIC TICKET
GET : http://localhost:3001/v1/ticket/607e65a3ad89063970b64a5c
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIzQGdtYWlsLmNvbSIsImlhdCI6MTYxODU5MjAxMiwiZXhwIjoxNjE4NTkzODEyfQ.yqYLDB-1CbumaQr2ojt1O81QqdPs7KOMjF-R8xlPjWc
 